default:
  workspace: shared

checkout:
  depth: 1

stages:
  - Install
  - Test

jobs:
  - name: Yarn install
    stage: Install
    image: node:16-alpine
    script:
      - yarn
    cache:
      - key:
          files:
            - yarn.lock
        paths:
          - node_modules

  - name: Composer install
    stage: Install
    image: sunasteriskrnd/php-workspace:8.1-alpine
    script:
      - composer install --ignore-platform-reqs
    cache:
      - key:
          files:
            - composer.lock
        paths:
          - vendor

  - name: ESLint
    stage: Test
    image: node:16-alpine
    script:
      - yarn lint

  - name: PHP CodeSniffer
    stage: Test
    image: sunasteriskrnd/php-workspace:8.1-alpine
    script:
      - composer cs

  - name: Composer analysis
    stage: Test
    image: sunasteriskrnd/php-workspace:8.1-alpine
    script:
      - composer analyze

  - name: PHPUnit
    stage: Test
    image: sunasteriskrnd/php-workspace:8.1-alpine
    services:
      - image: postgres:10.8
        environment:
          - POSTGRES_DB=test
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
    environment:
      - APP_ENV=testing
    before_script:
      - echo 'memory_limit=-1' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini
    script:
      - docker-php-ext-disable xdebug
      - cp .env.example .env.testing
      - php artisan key:generate --quiet
      - php artisan migrate
      - composer coverage
    artifacts:
      paths:
        - coverage
      expires_in: 3 days
