on: push
name: CI-with-cache

env:
  LARAVEL_BYPASS_ENV_CHECK: 1

jobs:
  yarn-install:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Add build dependencies to container
        run: |
          apk add --update --no-progress \
          tar

      - name: Restore yarn cache
        id: node-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Yarn install
        run: yarn install

      - name: Yarn caching
        uses: actions/cache/save@v3
        id: node-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}

  eslint:
    needs: yarn-install
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Restore yarn cache
        id: node-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Yarn lint
        run: yarn lint --max-warnings 0

  composer-install:
    runs-on: ubuntu-latest
    container:
      image: sunasteriskrnd/php-workspace:8.1-alpine
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Restore composer cache
        id: composer-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer install
        run: |
          composer install --ignore-platform-reqs

      - name: Composer caching
        uses: actions/cache/save@v3
        id: composer-cache
        with:
          path: vendor
            key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

  composer-codesniffer:
    needs: composer-install
    runs-on: ubuntu-latest
    container:
      image: sunasteriskrnd/php-workspace:8.1-alpine

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Restore composer cache
        id: composer-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: PHP CodeSniffer
        run: composer cs

  composer-analysis:
    needs: composer-install
    runs-on: ubuntu-latest
    container:
      image: sunasteriskrnd/php-workspace:8.1-alpine

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Restore composer cache
        id: composer-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer analysis
        run: composer analyze

  phpunit:
    needs: composer-install
    runs-on: ubuntu-latest
    container:
      image: sunasteriskrnd/php-workspace:8.1-alpine

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Restore composer cache
        id: composer-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: PHPUnit
        env:
          APP_ENV: testing
        run: |
          echo 'memory_limit=-1' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini
          docker-php-ext-disable xdebug
          cp .env.example .env.testing
          php artisan key:generate --quiet
          php artisan migrate
          composer coverage

      - name: 'Upload coverage artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Coverage
          path: coverage
          retention-days: 5
